"""Variables"""
vocab_path = "vocab/"


"""Texte"""
welcome_text = "Willkommen bei Vokaba"
settings_title_text = "Settings"
settings_title_font_size_slider = "Titelgröße anpassen"
settings_title_font_size_slider_test_label = "Titelgröße"
add_stack_title_text = "Stapel Hinzufügen"
add_stack_title_text_empty = "Fehler: Eine Box ist nicht ausgefüllt"
add_stack_title_text_exists = "Fehler: Dieser Stapelnahme ist schon vergeben"
add_stack_filename = "Stapelname:"
add_own_language = "Eigene Sprache:"
add_foreign_language = "Fremdsprache:"
add_third_column = "Dritte Spalte:"
add_additional_info = "Mehr Infos: "
add_vocabulary_button_text = "Vokabel Hinzufügen"
three_digit_toggle = "            3-Spaltig:"
add_stack_button_text = "Stapel Hinzufügen"
delete_stack_button = "Stapel löschen"
caution = "[color=ff0000]ACHTUNG[/color]"
delete_stack_confirmation_text = "[color=ff0000]Dieser Stapel wird gelöscht.[/color]"
cant_be_undone = "[color=ff0000]Dies kann nicht rückgängig gemacht werden![/color]"
cancel = "abbrechen"
delete = "[color=ff0000]löschen[/color]"
add_vocab_button_text = "Vokabeln hinzufügen"
